name: Upload component to ESP registry

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:  # This line enables manual triggering

jobs:
  upload_components:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Upload component to the registry
        uses: espressif/upload-components-ci-action@v1
        with:
          namespace: "hayschan"
          name: "max6675"
          version: ${{ github.ref_name }}
          api_token: ${{ secrets.IDF_COMPONENT_API_TOKEN }}
